Repository ichiro-its/kumo-client, pull requests merged in 2021-03, with the labels that each got.

#2 1 create an example for a subscription client
  .gitignore
  LICENSE
  README.md
  examples/subscription.html
  package.json
Labels: enhancement

#4 add support for subscription destroy
  examples/subscription.html
Labels: enhancement

#5 Minor modify according to ichiro-its/kumo#11
  examples/subscription.html
Labels: enhancement

#6 3 create modules for the library
  .gitignore
  examples/create_node.js
  examples/subscription.html
  index.js
  package.json
  src/handlers/base_handler.ts
  src/handlers/context_handler.ts
  src/handlers/index.ts
  src/handlers/node_handler.ts
  src/handlers/subscription_handler.ts
  src/index.ts
  src/message.ts
  src/session.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#9 Added kumo_ci.yml
  .github/workflows/kumo_ci.yml
Labels: enhancement, good first issue

#10 7 add linter
  .eslintrc.json
  .github/workflows/kumo_ci.yml
  .github/workflows/kumo_client_ci.yml
  examples/.eslintrc.json
  examples/simple_subscription.js
  package.json
  src/handlers/base_handler.ts
  src/handlers/context_handler.ts
  src/handlers/index.ts
  src/handlers/node_handler.ts
  src/handlers/subscription_handler.ts
  src/index.ts
  src/message.ts
  src/session.ts
  yarn.lock
Labels: enhancement

#14 11 add support for destroy node
  examples/simple_subscription.js
  src/handlers/node_handler.ts
  src/message.ts
Labels: enhancement

#15 Add support for create, destroy, and publish Publisher
  examples/simple_publisher.js
  examples/simple_subscription.js
  src/handlers/base_handler.ts
  src/handlers/context_handler.ts
  src/handlers/node_handler.ts
  src/handlers/publisher_handler.ts
  src/handlers/subscription_handler.ts
  src/message.ts
Labels: enhancement

#20 Add .npmignore
  .npmignore
  package.json
Labels: bug

#21 Add support for create, destroy, and call Client
  examples/simple_client.js
  src/handlers/client_handler.ts
  src/handlers/node_handler.ts
  src/message.ts
Labels: enhancement

#22 16 add support for ros2 service
  examples/simple_service.js
  src/handlers/node_handler.ts
  src/handlers/service_handler.ts
  src/handlers/subscription_handler.ts
  src/message.ts
Labels: enhancement

#23 18 auto generate the library documentation
  .github/workflows/build-and-lint.yml
  .github/workflows/doc-and-deploy.yml
  .gitignore
  package.json
  src/handlers/index.ts
  typedoc.json
  yarn.lock
Labels: documentation, enhancement

#26 Replacing WebSocketClient with W3CWebSocket
  examples/simple_client.js
  examples/simple_publisher.js
  examples/simple_service.js
  examples/simple_subscription.js
  package.json
  src/handlers/base_handler.ts
  src/session.ts
Labels: bug

#27 Update information in the readme file
  README.md
  package.json
Labels: documentation

#30 29 modify context handler into session handler
  .npmignore
  README.md
  examples/simple_client.js
  examples/simple_publisher.js
  examples/simple_service.js
  examples/simple_subscription.js
  package.json
  src/bridge.ts
  src/handlers/index.ts
  src/handlers/session_handler.ts
  src/index.ts
Labels: bug, enhancement, good first issue
