Repository ichiro-its/kumo-client, pull requests merged in 2021-04, with the labels that each got.

#34 Add keywords and update informations
  LICENSE
  README.md
  package.json
Labels: documentation

#36 Add prepare script and modify informations
  package-lock.json
  package.json
Labels: enhancement, good first issue

#38 37 modify callback
  .eslintignore
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  src/handlers/node_handler.ts
  src/handlers/service_handler.ts
  src/handlers/subscription_handler.ts
  tsconfig.json
Labels: enhancement, good first issue

#40 fix: add reject on brdige connect
  src/bridge.ts
Labels: bug

#41 docs: update version to 0.2.4
  package-lock.json
  package.json
Labels: documentation
